### PR TITLE
Check for github action updates monthly

### PR DESCRIPTION
**Pull request by jlosito**
*Issue #, if available:*

N/A

*Description of changes:*

This will use dependabot to check for updates on github actions which this project uses on a monthly basis.

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kddejong** [comment]
I have sub folders under client/ and server/  Will this work for that?

**Comment by jlosito** [comment]
@kddejong Sure will. Would you like me to add the npm related sections for both of these?

**Comment by kddejong** [comment]
@jlosito that would be great.   Thank you.

**Comment by jlosito** [comment]
@kddejong The additional sub-directories should be tracked now apart of the pull request.

**Pull request merged**
